class Domaine < ApplicationRecord
  has_many :actions
  has_many :campains
  has_many :campain_configs
  has_many :campain_test_suites
  has_many :campain_test_suite_forced_configs
  has_many :computers
  has_many :computer_last_gets
  has_many :configuration_variables
  has_many :configuration_variable_values
  has_many :cycles
  has_many :default_user_configs
  has_many :domelements
  has_many :environnements
  has_many :environnement_variables
  has_many :data_sets
  has_many :data_set_variables
  has_many :findstrategies
  has_many :funcandscreens
  has_many :links
  has_many :listes
  has_many :liste_values
  has_many :lockobjects
  has_many :nodes
  has_many :node_forced_computers
  has_many :node_forced_configs
  has_many :procedures
  has_many :procedure_actions
  has_many :projects
  has_many :releases
  has_many :required_gems
  has_many :roles
  has_many :runs
  has_many :run_authentications
  has_many :run_configs
  has_many :run_screenshots
  has_many :run_step_results
  has_many :run_suite_schemes
  has_many :run_store_data
  has_many :sheets
  has_many :sheet_folders
  has_many :tests
  has_many :test_constantes
  has_many :test_folders
  has_many :test_steps
  has_many :users
  has_many :userprojects
  has_many :user_notifications
  has_many :versions
  has_many :type_fiches 
  has_many :fiches 
  has_many :fiche_custo_fields
  has_many :fiche_histos 
  has_many :link_obj_versions
  has_many :project_versions
  has_many :kanbans
  has_many :kanban_statuses
  has_many :kanban_type_fiches
  has_many :kanban_filters
  has_many :fiche_links
  has_many :fiche_downloads
  has_many :run_ended_nodes
  has_many :ref_screenshots
end
